# Generated by Django 3.0.2 on 2020-03-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='expire_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
