# Generated by Django 3.0.2 on 2020-03-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_activityperiod_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
