# Generated by Django 3.0.2 on 2020-03-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200324_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='offer',
            new_name='offer_id',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Offers'),
        ),
    ]
