# Generated by Django 3.0.2 on 2020-03-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200325_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Offers'),
        ),
    ]
